// MTE MK1 (la Churrera) v5.0
// Copyleft 2010-2014, 2020 by the Mojon Twins

// Generated by The Librarian v2.0 20200202
// Copyleft 2020 by The Mojon Twins

typedef struct {
    unsigned char ramPage;
    unsigned int ramOffset;
} RESOURCE;

RESOURCE resources [] = {
    { 3, 0xC000 },
    { 3, 0xC641 },
    { 3, 0xCBD4 },
    { 3, 0xD115 }
};

#define LEVEL0C_BIN                     0
#define TITLE_BIN                       1
#define ENDING_BIN                      2
#define MARCO_BIN                       3

